[package]
name = "linux_proc"
version = "0.1.0"
authors = ["pearzl <302669696@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = ["all"]
all = []
apm = []